# Note:
#
# Please keep rules alphabetized within their sections (Style, Metrics, etc)
# Please keep sections alphabetized and separated from other sections

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - gemfiles/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 15
  Exclude:
    - test/**/*

Metrics/ModuleLength:
  Exclude:
    - test/**/*

Metrics/PerceivedComplexity:
  Max: 16

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Max: 100

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 10

Naming/AccessorMethodName:
  Exclude:
    - lib/ae_active_job_state/has_job_state.rb
